import { InventoryItem, StockAdjustment } from "@/types/inventory";

export const mockInventory: InventoryItem[] = [
  {
    id: "1",
    name: "Wireless Mouse",
    sku: "WM-001",
    category: "Electronics",
    quantity: 45,
    minStock: 20,
    unit: "pcs",
    costPrice: 15.50,
    sellingPrice: 29.99,
    supplier: "Tech Supplies Co",
    lastRestocked: "2025-10-05",
    location: "Shelf A1",
  },
  {
    id: "2",
    name: "USB-C Cable",
    sku: "UC-002",
    category: "Electronics",
    quantity: 12,
    minStock: 30,
    unit: "pcs",
    costPrice: 5.00,
    sellingPrice: 12.99,
    supplier: "Cable World",
    lastRestocked: "2025-09-28",
    location: "Shelf A2",
  },
  {
    id: "3",
    name: "Notebook A4",
    sku: "NB-003",
    category: "Stationery",
    quantity: 150,
    minStock: 50,
    unit: "pcs",
    costPrice: 2.50,
    sellingPrice: 5.99,
    supplier: "Office Supplies Ltd",
    lastRestocked: "2025-10-08",
    location: "Shelf B1",
  },
  {
    id: "4",
    name: "Blue Pen Pack",
    sku: "BP-004",
    category: "Stationery",
    quantity: 8,
    minStock: 25,
    unit: "pack",
    costPrice: 3.00,
    sellingPrice: 7.49,
    supplier: "Office Supplies Ltd",
    lastRestocked: "2025-09-15",
    location: "Shelf B2",
  },
  {
    id: "5",
    name: "Desk Lamp",
    sku: "DL-005",
    category: "Furniture",
    quantity: 18,
    minStock: 10,
    unit: "pcs",
    costPrice: 25.00,
    sellingPrice: 49.99,
    supplier: "Home & Office",
    lastRestocked: "2025-10-01",
    location: "Shelf C1",
  },
];

export const mockAdjustments: StockAdjustment[] = [
  {
    id: "1",
    itemId: "2",
    itemName: "USB-C Cable",
    previousQty: 30,
    newQty: 12,
    adjustment: -18,
    reason: "Sales",
    date: "2025-10-10",
    user: "Admin",
  },
  {
    id: "2",
    itemId: "4",
    itemName: "Blue Pen Pack",
    previousQty: 25,
    newQty: 8,
    adjustment: -17,
    reason: "Sales",
    date: "2025-10-09",
    user: "Admin",
  },
  {
    id: "3",
    itemId: "3",
    itemName: "Notebook A4",
    previousQty: 100,
    newQty: 150,
    adjustment: 50,
    reason: "Restock",
    date: "2025-10-08",
    user: "Admin",
  },
];
